# Hand-authored initial migration for the packaged production scaffold.
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial=True
    dependencies=[]
    operations=[
        migrations.CreateModel(name="Source", fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("name",models.CharField(max_length=160)),("source_type",models.CharField(choices=[("official","Official authority"),("discovery","Discovery/reference only")],default="official",max_length=16)),("base_url",models.URLField()),("entry_url",models.URLField()),("enabled",models.BooleanField(default=True)),("trust_score",models.FloatField(default=1.0)),("crawl_interval_minutes",models.PositiveIntegerField(default=240)),("max_links_per_scan",models.PositiveIntegerField(default=80)),("allow_store_body",models.BooleanField(default=False)),("extra_allowed_domains",models.JSONField(blank=True,default=list)),("user_agent",models.CharField(default="SarkariNaukriBot/1.0 (+source-verification)",max_length=200)),("notes",models.TextField(blank=True)),("last_scanned_at",models.DateTimeField(blank=True,null=True)),("last_status",models.CharField(blank=True,max_length=120)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True))],options={"ordering":["source_type","name"]}),
        migrations.CreateModel(name="Job", fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("slug",models.SlugField(max_length=220,unique=True)),("title",models.CharField(max_length=320)),("organization",models.CharField(max_length=240)),("advertisement_no",models.CharField(blank=True,max_length=120)),("post_name",models.CharField(blank=True,max_length=240)),("summary",models.TextField(blank=True)),("vacancies",models.PositiveIntegerField(blank=True,null=True)),("qualifications",models.JSONField(blank=True,default=list)),("qualification_group",models.CharField(blank=True,db_index=True,max_length=80)),("sector",models.CharField(blank=True,db_index=True,max_length=80)),("state",models.CharField(blank=True,db_index=True,max_length=80)),("location",models.CharField(blank=True,max_length=160)),("salary",models.CharField(blank=True,max_length=240)),("age_limit",models.CharField(blank=True,max_length=240)),("application_fee",models.CharField(blank=True,max_length=320)),("selection_process",models.TextField(blank=True)),("application_start_date",models.DateField(blank=True,null=True)),("application_end_date",models.DateField(blank=True,db_index=True,null=True)),("official_notification_url",models.URLField(max_length=1000)),("official_apply_url",models.URLField(blank=True,max_length=1000)),("official_website_url",models.URLField(blank=True,max_length=1000)),("source_url",models.URLField(max_length=1000)),("source_hash",models.CharField(db_index=True,max_length=64)),("discovered_via",models.CharField(blank=True,max_length=160)),("discovery_url",models.URLField(blank=True,max_length=1000)),("evidence_urls",models.JSONField(blank=True,default=list)),("verification_confidence",models.FloatField(default=0.0)),("verified_at",models.DateTimeField(blank=True,null=True)),("status",models.CharField(choices=[("draft","Draft"),("review","Needs review"),("published","Published"),("expired","Expired"),("cancelled","Cancelled")],db_index=True,default="draft",max_length=16)),("first_seen_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("published_at",models.DateTimeField(blank=True,null=True)),("change_version",models.PositiveIntegerField(default=1)),("is_featured",models.BooleanField(default=False))],options={"ordering":["-published_at","application_end_date"]}),
        migrations.CreateModel(name="AdmitCard",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("slug",models.SlugField(max_length=220,unique=True)),("title",models.CharField(max_length=320)),("organization",models.CharField(max_length=240)),("exam_name",models.CharField(blank=True,max_length=240)),("release_date",models.DateField(blank=True,null=True)),("exam_date",models.CharField(blank=True,max_length=180)),("official_url",models.URLField(max_length=1000)),("source_url",models.URLField(max_length=1000)),("source_hash",models.CharField(max_length=64)),("verification_confidence",models.FloatField(default=0)),("verified_at",models.DateTimeField(blank=True,null=True)),("status",models.CharField(choices=[("review","Needs review"),("published","Published"),("archived","Archived")],default="review",max_length=16)),("created_at",models.DateTimeField(auto_now_add=True))],options={"ordering":["-release_date","-created_at"]}),
        migrations.CreateModel(name="Result",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("slug",models.SlugField(max_length=220,unique=True)),("title",models.CharField(max_length=320)),("organization",models.CharField(max_length=240)),("exam_name",models.CharField(blank=True,max_length=240)),("result_date",models.DateField(blank=True,null=True)),("official_url",models.URLField(max_length=1000)),("source_url",models.URLField(max_length=1000)),("source_hash",models.CharField(max_length=64)),("verification_confidence",models.FloatField(default=0)),("verified_at",models.DateTimeField(blank=True,null=True)),("status",models.CharField(choices=[("review","Needs review"),("published","Published"),("archived","Archived")],default="review",max_length=16)),("created_at",models.DateTimeField(auto_now_add=True))],options={"ordering":["-result_date","-created_at"]}),
        migrations.CreateModel(name="ChangeEvent",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("object_type",models.CharField(max_length=30)),("object_pk",models.PositiveBigIntegerField()),("title",models.CharField(max_length=320)),("field_changes",models.JSONField(default=dict)),("source_url",models.URLField(blank=True,max_length=1000)),("created_at",models.DateTimeField(auto_now_add=True))],options={"ordering":["-created_at"]}),
        migrations.CreateModel(name="CrawlRun",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("started_at",models.DateTimeField(auto_now_add=True)),("completed_at",models.DateTimeField(blank=True,null=True)),("status",models.CharField(choices=[("running","Running"),("ok","OK"),("partial","Partial"),("failed","Failed")],default="running",max_length=16)),("discovered_count",models.PositiveIntegerField(default=0)),("published_count",models.PositiveIntegerField(default=0)),("updated_count",models.PositiveIntegerField(default=0)),("error_count",models.PositiveIntegerField(default=0)),("log",models.JSONField(blank=True,default=list)),("source",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="runs",to="portal.source"))],options={"ordering":["-started_at"]}),
        migrations.CreateModel(name="DiscoverySignal",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("external_url",models.URLField(max_length=1000)),("headline",models.CharField(max_length=500)),("normalized_key",models.CharField(db_index=True,max_length=64)),("official_resolved_url",models.URLField(blank=True,max_length=1000)),("status",models.CharField(choices=[("new","New"),("resolved","Resolved"),("ignored","Ignored"),("review","Needs review")],default="new",max_length=16)),("detected_at",models.DateTimeField(auto_now_add=True)),("source",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="signals",to="portal.source"))],options={"ordering":["-detected_at"]}),
        migrations.CreateModel(name="SourceDocument",fields=[("id",models.BigAutoField(primary_key=True,serialize=False)),("url",models.URLField(max_length=1000,unique=True)),("title",models.CharField(blank=True,max_length=500)),("classification",models.CharField(blank=True,max_length=30)),("content_hash",models.CharField(db_index=True,max_length=64)),("content_text",models.TextField(blank=True)),("excerpt",models.TextField(blank=True)),("links",models.JSONField(blank=True,default=list)),("first_seen_at",models.DateTimeField(auto_now_add=True)),("last_fetched_at",models.DateTimeField(auto_now=True)),("http_etag",models.CharField(blank=True,max_length=300)),("http_last_modified",models.CharField(blank=True,max_length=300)),("source",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="documents",to="portal.source"))],options={"ordering":["-last_fetched_at"]}),
        migrations.AddConstraint(model_name="discoverysignal",constraint=models.UniqueConstraint(fields=("source","external_url"),name="unique_signal_per_source")),
        migrations.AddIndex(model_name="job",index=models.Index(fields=["status","application_end_date"],name="portal_job_status_8cb0e2_idx")),
        migrations.AddIndex(model_name="job",index=models.Index(fields=["organization","advertisement_no"],name="portal_job_organiz_71a38e_idx")),
    ]
