from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="job", name="accepted_disciplines", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="job", name="eligible_categories", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="job", name="eligible_genders", field=models.JSONField(blank=True, default=list)),
        migrations.AddField(model_name="job", name="employment_type", field=models.CharField(blank=True, default="Government", max_length=80)),
        migrations.AddField(model_name="job", name="min_age", field=models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="job", name="max_age", field=models.PositiveSmallIntegerField(blank=True, null=True)),
        migrations.AddField(model_name="job", name="age_as_on", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="job", name="category_age_relaxation", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="job", name="min_experience_months", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="job", name="fee_by_category", field=models.JSONField(blank=True, default=dict)),
        migrations.AddField(model_name="job", name="exam_date", field=models.DateField(blank=True, db_index=True, null=True)),
        migrations.AddField(model_name="job", name="admit_card_date", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="job", name="result_date", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="job", name="is_postponed", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="job", name="important_update", field=models.CharField(blank=True, max_length=500)),
        migrations.AddIndex(model_name="job", index=models.Index(fields=["sector", "qualification_group", "state"], name="portal_job_sector_qual_state_idx")),

        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("education", models.CharField(blank=True, max_length=80)),
                ("discipline", models.CharField(blank=True, max_length=160)),
                ("state", models.CharField(blank=True, max_length=80)),
                ("category", models.CharField(choices=[("General","General"),("EWS","EWS"),("OBC","OBC"),("SC","SC"),("ST","ST"),("PwBD","PwBD"),("Other","Other")], default="General", max_length=20)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("experience_months", models.PositiveIntegerField(default=0)),
                ("preferred_qualifications", models.JSONField(blank=True, default=list)),
                ("preferred_sectors", models.JSONField(blank=True, default=list)),
                ("preferred_states", models.JSONField(blank=True, default=list)),
                ("language", models.CharField(choices=[("en","English"),("hi","हिन्दी")], default="en", max_length=4)),
                ("email_alerts", models.BooleanField(default=True)),
                ("push_alerts", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="job_preferences", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254)),
                ("qualifications", models.JSONField(blank=True, default=list)),
                ("sectors", models.JSONField(blank=True, default=list)),
                ("states", models.JSONField(blank=True, default=list)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("frequency", models.CharField(choices=[("instant","Instant"),("daily","Daily digest")], default="daily", max_length=12)),
                ("confirmed", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="job_alerts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering":["-created_at"]},
        ),
        migrations.AddIndex(model_name="alertsubscription", index=models.Index(fields=["active","frequency"], name="portal_alert_active_freq_idx")),
        migrations.CreateModel(
            name="ExamEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(choices=[("apply_start","Application starts"),("apply_end","Application deadline"),("exam","Exam"),("admit","Admit card"),("result","Result")], max_length=20)),
                ("title", models.CharField(max_length=320)),
                ("organization", models.CharField(blank=True, max_length=240)),
                ("event_date", models.DateField(db_index=True)),
                ("official_url", models.URLField(blank=True, max_length=1000)),
                ("auto_generated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="exam_events", to="portal.job")),
            ],
            options={"ordering":["event_date","title"]},
        ),
        migrations.AddConstraint(model_name="examevent", constraint=models.UniqueConstraint(fields=("job","event_type","event_date"), name="unique_job_exam_event")),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("query", models.CharField(max_length=240)),
                ("normalized", models.CharField(max_length=240, unique=True)),
                ("count", models.PositiveIntegerField(default=1)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering":["-count","-last_seen_at"]},
        ),
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("saved","Saved"),("applied","Applied"),("exam","Exam scheduled"),("result","Result / completed")], default="saved", max_length=16)),
                ("notes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_by", to="portal.job")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering":["-updated_at"]},
        ),
        migrations.AddConstraint(model_name="savedjob", constraint=models.UniqueConstraint(fields=("user","job"), name="unique_saved_job")),
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(choices=[("view","Job view"),("search","Search"),("apply_click","Apply click"),("notification_click","Notification click"),("website_click","Official website click"),("save","Save job"),("alert_signup","Alert signup"),("eligibility","Eligibility check")], db_index=True, max_length=32)),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=64)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="analytics_events", to="portal.job")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering":["-created_at"]},
        ),
        migrations.AddIndex(model_name="analyticsevent", index=models.Index(fields=["event_type","created_at"], name="portal_analytics_type_time_idx")),
        migrations.CreateModel(
            name="SourceHealthCheck",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("ok","OK"),("warn","Warning"),("fail","Failed")], max_length=10)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="health_checks", to="portal.source")),
            ],
            options={"ordering":["-checked_at"]},
        ),
        migrations.AddIndex(model_name="sourcehealthcheck", index=models.Index(fields=["source","-checked_at"], name="portal_source_health_idx")),
        migrations.CreateModel(
            name="LinkCheck",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.URLField(max_length=1000)),
                ("kind", models.CharField(choices=[("apply","Apply URL"),("notification","Notification URL"),("website","Official website")], max_length=20)),
                ("ok", models.BooleanField(default=False)),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="link_checks", to="portal.job")),
            ],
            options={"ordering":["-checked_at"]},
        ),
        migrations.AddIndex(model_name="linkcheck", index=models.Index(fields=["job","kind","-checked_at"], name="portal_link_job_kind_idx")),
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("endpoint", models.URLField(max_length=1200, unique=True)),
                ("p256dh", models.CharField(max_length=300)),
                ("auth", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="web_push_subscriptions", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("channel", models.CharField(choices=[("email","Email"),("push","Push")], max_length=12)),
                ("notification_type", models.CharField(max_length=40)),
                ("dedupe_key", models.CharField(max_length=180, unique=True)),
                ("status", models.CharField(choices=[("sent","Sent"),("failed","Failed"),("skipped","Skipped")], max_length=12)),
                ("detail", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="portal.job")),
                ("subscription", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="portal.alertsubscription")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering":["-created_at"]},
        ),
    ]
